// Code generated by "stringer -type=CFGType"; DO NOT EDIT.

package cfg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INT_TYPE-0]
	_ = x[INT_ARRAY_TYPE-1]
	_ = x[STRING_TYPE-2]
	_ = x[STRING_ARRAY_TYPE-3]
	_ = x[FLOAT_TYPE-4]
	_ = x[FLOAT_ARRAY_TYPE-5]
	_ = x[BOOL_TYPE-6]
	_ = x[BOOL_ARRAY_TYPE-7]
}

const _CFGType_name = "INT_TYPEINT_ARRAY_TYPESTRING_TYPESTRING_ARRAY_TYPEFLOAT_TYPEFLOAT_ARRAY_TYPEBOOL_TYPEBOOL_ARRAY_TYPE"

var _CFGType_index = [...]uint8{0, 8, 22, 33, 50, 60, 76, 85, 100}

func (i CFGType) String() string {
	if i < 0 || i >= CFGType(len(_CFGType_index)-1) {
		return "CFGType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CFGType_name[_CFGType_index[i]:_CFGType_index[i+1]]
}
